Homework 2
Kratlis/EkaterinaKubikova pull request #2
Opened 2021-08-13 21:22 UTC by Kratlis

2021-08-17 18:29 UTC, shoggy requested changes
I put comments for first occurrences of issues, please make appropriate fixes in other places too

2021-08-17 18:29 UTC, shoggy commented on src/test/java/com/epam/tc/hw2/ex1/HomePageTest.java
> +            By.xpath("//a[@href='#']")
Dangerous locator, maybe you can use another one?

2021-08-17 18:29 UTC, shoggy commented on pom.xml
> +    </dependency>
candidate for `scope:test`

2021-08-17 18:29 UTC, shoggy commented on src/test/java/com/epam/tc/hw2/ex1/HomePageTest.java
> +
SoftAssert is created in each of the methods, but I think would be better to create it once in the `@Test` method and pass it  to subsequent calls

2021-08-17 18:29 UTC, shoggy commented on src/test/java/com/epam/tc/hw2/ex1/HomePageTest.java
> +        }
Lets try to convert menuButtons to list of strings and compare like `assertThat(actualStringCollection).isEqualTo(expectedStringCollection)`

2021-08-17 18:29 UTC, shoggy commented on src/test/java/com/epam/tc/hw2/ex1/HomePageTest.java
> +        softAssert.assertEquals(imagesNumber, Utils.IMAGES_NUMBER);
There is matcher for collection size, something like `assertThat(collection).hasSize(...)`

2021-08-17 18:29 UTC, shoggy commented on src/test/java/com/epam/tc/hw2/ex1/HomePageTest.java
> +        }
Using asserts inside loops is not a good practice. AssertJ provides a method that checks all of the elements meet some criteria, something like `matchAll`

2021-08-17 18:29 UTC, shoggy commented on src/test/java/com/epam/tc/hw2/ex1/HomePageTest.java
> +        }
same here
get collection of texts and compare it using one matcher

2021-08-17 18:29 UTC, shoggy commented on src/test/java/com/epam/tc/hw2/ex1/HomePageTest.java
> +        }
do you mean `finally`?

2021-08-17 18:29 UTC, shoggy commented on src/test/java/com/epam/tc/hw2/ex1/Utils.java
> +            By.xpath("//span[contains(@class, 'icon-base')]/../following-sibling::*[@class='benefit-txt']"))
Please use one locator, that does not depends on specific `icon-*`

2021-08-17 18:29 UTC, shoggy commented on src/test/java/com/epam/tc/hw2/ex1/Utils.java
> +        Arrays.asList(
`new ArrayList<>(Arrays.asList(` -- is redundant. This can be simplified to `Arrays.asList(` or even `List.of(`

2021-08-17 18:29 UTC, shoggy commented on src/test/java/com/epam/tc/hw2/ex1/Utils.java
> +    public static final int LEFT_SECTION_ITEMS_NUM = 5;
This number is extra, it can be calculated as `left.....size()`

2021-08-17 18:29 UTC, shoggy commented on src/test/java/com/epam/tc/hw2/ex1/Utils.java
> +        System.setProperty(CHROME_SYSTEM_PROPERTY_NAME, CHROME_SYSTEM_PROPERTY_PATH);
Dangerous step, because this build works only on your machine. I suggest to use bonigarcia webdrivermanager

2021-08-23 20:29 UTC, shoggy requested changes
Please combine two Utils classes into one
Create parent class for Test classes and move common logic into this class

2021-08-26 14:54 UTC, ZeroShadows approved these changes

2021-08-26 14:57 UTC, merged